### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not ...

### ISSUE THREAD

**Issue by jschilperoord** [subesokun/atom-tree-view-git-status#29] opened 2016-06-13 18:24 UTC
Right click in tree view. And dan click on "Add project folder". Select folder to add to project. And click on OK. 

After this the error popped up.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v1.0.0
### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At /Users/Jeffrey/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:107

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at /Users/Jeffrey/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:107:28
    at Map.forEach (native)
    at TreeViewUI.module.exports.TreeViewUI.clearTreeViewRootMap (/Users/Jeffrey/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:103:24)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/Users/Jeffrey/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:116:8)
    at /Users/Jeffrey/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:48:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:263:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:948:41
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
     -0:14.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/Jeffrey/Projects",
    "themes": [
      "nucleus-dark-ui",
      "adventurous-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
adventurous-syntax, v0.2.0
atom-jade, v0.3.0
color-picker, v2.1.1
minimap, v4.24.4
nucleus-dark-ui, v0.8.3
pigments, v0.29.2
tabs-to-spaces, v1.0.2
tree-view-git-status, v1.0.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by subesokun** [comment] 2016-06-14 05:34
@jschilperoord, thanks for reporting! It looks like some unhandled race condition, I'll try to get soon a bugfix ready for that. Is this error always occurring or only sporadic?

**Comment by jschilperoord** [comment] 2016-06-14 05:35
Only sporadic. I'll report back when its occurring more frequently 👍

**Comment by crucialfelix** [comment] 2016-06-20 16:18
I'm getting this as well. 

I'm adding and removing project folders using `atom.project.addPath` / `atom.project.removePath`

Basically the same error as @jschilperoord posted above:

```
-ctags:readTags] /Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/Hadron/.tags start...
ctags-cache.coffee:38 [atom-ctags:readTags] /Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/HadronPlugins/.tags start...
ctags-cache.coffee:38 [atom-ctags:readTags] /Users/crucial/supercolliderjs/lib/sc-classes/.tags start...
ctags-cache.coffee:38 [atom-ctags:readTags] /Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/ServerOptionsGui/.tags start...
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/exception-reporting/lib/main.js:25 Error reporting uncaught exception Error: Cannot find module '../package.json'(…)(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/exception-reporting/lib/main.js:25module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:832
treeviewui.coffee:107 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.(anonymous function) @ treeviewui.coffee:107module.exports.TreeViewUI.clearTreeViewRootMap @ treeviewui.coffee:103module.exports.TreeViewUI.updateRoots @ treeviewui.coffee:116(anonymous function) @ treeviewui.coffee:48module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125module.exports.Project.removePath @ /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:289module.exports.Controller.updateProjectFolders @ controller.coffee:335module.exports.Controller.handleReplEvent @ controller.coffee:77(anonymous function) @ controller.coffee:64(anonymous function) @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:395Bacon.UpdateBarrier.inTransaction @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:368Dispatcher.push @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:1142Dispatcher.handleEvent @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:1195(anonymous function) @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:232extend.push @ /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:2268(anonymous function) @ repl.coffee:151emitOne @ events.js:82emit @ events.js:169(anonymous function) @ sclang.js:252emitOne @ events.js:77emit @ events.js:169setState @ sclang-io.js:84fn @ sclang-io.js:164(anonymous function) @ sclang-io.js:59parse @ sclang-io.js:53(anonymous function) @ sclang.js:274emitOne @ events.js:77emit @ events.js:169readableAddChunk @ _stream_readable.js:146Readable.push @ _stream_readable.js:110onread @ net.js:523
ctags-cache.coffee:55 [atom-ctags:readTags] /Users/crucial/code/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/.tags cost: 264ms
```

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.2
**Thrown From**: [tree-view-git-status](https://github.com/subesokun/atom-tree-view-git-status) package, v1.0.0

### Stack Trace

Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

```
At /Users/crucial/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:107

Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at /Users/crucial/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:107:28
    at Map.forEach (native)
    at TreeViewUI.module.exports.TreeViewUI.clearTreeViewRootMap (/Users/crucial/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:103:24)
    at TreeViewUI.module.exports.TreeViewUI.updateRoots (/Users/crucial/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:116:8)
    at /Users/crucial/.atom/packages/tree-view-git-status/lib/treeviewui.coffee:48:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.removePath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:289:22)
    at Controller.module.exports.Controller.updateProjectFolders (/Users/crucial/github/atom-supercollider/lib/controller.coffee:335:26)
    at Controller.module.exports.Controller.handleReplEvent (/Users/crucial/github/atom-supercollider/lib/controller.coffee:77:10)
    at /Users/crucial/github/atom-supercollider/lib/controller.coffee:64:10
    at /Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:395:23
    at Object.Bacon.UpdateBarrier.inTransaction (/Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:368:11)
    at Dispatcher.push (/Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:1142:24)
    at Dispatcher.handleEvent (/Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:1195:17)
    at Observable.sink (/Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:232:17)
    at Observable.extend.push (/Users/crucial/github/atom-supercollider/node_modules/baconjs/dist/Bacon.js:2268:19)
    at SCLang.<anonymous> (/Users/crucial/github/atom-supercollider/lib/repl.coffee:151:17)
    at emitOne (events.js:82:20)
    at SCLang.emit (events.js:169:7)
    at SclangIO.<anonymous> (/Users/crucial/supercolliderjs/lib/lang/sclang.js:306:23)
    at emitOne (events.js:77:13)
    at SclangIO.emit (events.js:169:7)
    at SclangIO.setState (/Users/crucial/supercolliderjs/lib/lang/internals/sclang-io.js:114:14)
    at Object.fn (/Users/crucial/supercolliderjs/lib/lang/internals/sclang-io.js:186:20)
    at /Users/crucial/supercolliderjs/lib/lang/internals/sclang-io.js:88:21
    at Array.forEach (native)
    at SclangIO.parse (/Users/crucial/supercolliderjs/lib/lang/internals/sclang-io.js:82:31)
    at Socket.<anonymous> (/Users/crucial/supercolliderjs/lib/lang/sclang.js:337:29)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -0:17.7.0 supercollider:recompile (atom-text-editor.editor.is-focused.vim-mode.normal-mode)
     -0:07.4.0 supercollider:eval (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "cute-cursor",
      "language-go",
      "language-java",
      "term",
      "language-supercollider",
      "linter-rst",
      "rst-preview",
      "rst-preview",
      "ide-haskell",
      "remote-edit",
      "atomatigit",
      "minimap-highlight-selected",
      "atomic-emacs",
      "autoflow",
      "autosave",
      "background-tips",
      "easy-motion",
      "gist-it",
      "git-blame",
      "git-difftool",
      "term2",
      "web-view",
      "atom-terminal",
      "css-color-highlighting",
      "editor-stats",
      "selection-count",
      "fancy-new-file",
      "minimap-find-and-replace",
      "mobile-preview",
      "my-package",
      "org",
      "paredit",
      "autocomplete",
      "atom-color-highlight",
      "autocomplete-jedi",
      "bezier-curve-editor",
      "coffee-lint",
      "python-jedi",
      "next-occurrence",
      "linter-scss-lint",
      "linter-coffeelint",
      "grunt-runner",
      "typewriter-sounds",
      "ide-flow",
      "autocomplete-paths",
      "language-jsx",
      "atom-pair",
      "atom-runner",
      "auto-copyright",
      "cparts",
      "dash",
      "git-log",
      "jupyter-notebook",
      "language-ejs",
      "node-debugger",
      "processing",
      "zentabs",
      "language-ruby-on-rails",
      "linter-cpplint",
      "angularjs",
      "glist",
      "javascript-snippets",
      "language-docker",
      "language-swift",
      "linter-jsxhint",
      "markdown-pdf",
      "theme-switch",
      "todo-show",
      "typewriter",
      "language-javascript-jsx",
      "linter-jshint",
      "atom-ternjs",
      "symbols-view",
      "symbol-gen",
      "language-gfm",
      "python-iresolve",
      "atom-lupa",
      "tabs-to-spaces",
      "linter-jscs",
      "symbols-tree-view",
      "ctags-status",
      "tidalcycles"
    ],
    "followSymlinks": true,
    "ignoredNames": [
      "*.pyc",
      ".DS_Store",
      "tags"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "schelp-syntax"
    ],
    "themes": [
      "one-light-ui",
      "fizzy"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-commander, v0.7.0
atom-ctags, v4.5.2
atom-django, v0.3.2
autoclose-html, v0.23.0
autocomplete-python, v1.8.1
clipboard-plus, v0.5.1
color-picker, v2.1.1
cssnano, v1.1.0
cursor-history, v0.5.9
devdocs, v0.2.1
django-templates, v0.5.0
docblockr, v0.7.3
editorconfig, v1.4.1
emmet, v2.4.3
filesize, v0.4.2
fizzy, v0.16.0
html-entities, v0.4.0
imdone-atom, v1.3.29
jade-snippets, v0.5.0
language-clojure, v0.21.0
language-cmake, v0.2.0
language-crontab, v0.2.1
language-ini, v1.16.0
language-jade, v0.7.1
language-markdown, v0.14.0
language-matlab, v0.2.1
language-nginx, v0.6.1
language-restructuredtext, v0.16.0
linter, v1.11.11
linter-csslint, v1.3.2
linter-eslint, v7.2.3
linter-flake8, v1.13.2
linter-htmlhint, v1.2.1
linter-jade, v0.3.2
linter-pylama, v0.2.9
linter-python, v2.1.7
linter-sass-lint, v1.6.1
minimap, v4.24.6
narrow, v0.5.2
pain-split, v1.4.0
pdf-view, v0.50.0
pigments, v0.29.2
processing-language, v0.2.0
project-manager, v2.9.7
python-autopep8, v0.1.3
python-isort, v0.0.7
react, v0.15.0
regex-railroad-diagram, v0.16.0
set-syntax, v0.3.0
supercollider, v0.6.2
tab-control, v0.6.9
tree-view-git-status, v1.0.0
vim-mode, v0.65.1
vim-mode-clipboard-plus, v0.2.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by crucialfelix** [comment] 2016-06-20 16:38
Not sure if this is related (or causing it).  I also see this posted _twice_ when I first reload the project (I'm in development mode):

```
TypeError: Cannot read property 'indexOf' of undefined
    at GitRepositoryAsync.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository-async.js:1341:32)
    at [object Generator].next (native)
    at step (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository-async.js:13:273)
    at process._tickCallback (node.js:392:9)(anonymous function) @ treeviewui.coffee:140_tickCallback @ node.js:392
```

This is before any add/remove folders have been done. Fresh reload of this test project in Atom.

Note twice, which is odd in that I have currently 3 healthy git folders added to the project.

![screen shot 2016-06-20 at 18 36 25](https://cloud.githubusercontent.com/assets/218738/16202437/fe501d3c-3715-11e6-8436-787fab5a7d39.png)

**Comment by subesokun** [comment] 2016-06-20 20:48
This bug seems to be happening more likely on OSX. I've added a fix via 40bd042db5feb81efade7ccf8c706fbc007a6a83 which will hopefully solve this issue. For some reason this error doesn't get thrown on my machines so I can't reproduce it at the moment. 

Could you do me a favor and test the latest master?

```
apm uninstall tree-view-git-status
git clone https://github.com/subesokun/atom-tree-view-git-status.git
cd atom-tree-view-git-status
apm install && apm link
# Restart Atom
```

If the error has gone I'll prepare a new release.

**Comment by subesokun** [comment] 2016-06-20 20:55
@crucialfelix The `TypeError: Cannot read property 'indexOf' of undefined` sounds also not good but as it's getting thrown from the Git Repo Async library it's bit hard to debug. Hopefully this error won't affect the way how tree-view-git-status works but it needs to be investigated.

**Comment by crucialfelix** [comment] 2016-06-21 07:04
I've tested your fix and it no longer throws `Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

The exact test case for me is:

Programmatically do `atom.project.addPath / atom.project.removePath`

This is done in the not yet released update of https://github.com/crucialfelix/atom-supercollider

It still posts the indexOf error but that is unrelated and relatively harmless.

Thanks @subesokun !

**Comment by subesokun** [comment] 2016-06-21 17:57
Ok, thanks for the feedback :) I'll keep an eye on the other `indexOf` error. The version v1.0.1 will be released in a few moments.

**Closed as completed by subesokun** 2016-06-21 17:57 UTC
Labels: bug
